[project]
name = "efmcalc"
version = "0.1.1"
description = "Naive token & price estimator with simple text chunking."
readme = "README.md"
authors = [{name="Arseny Perel"}]
requires-python = ">=3.9"
dependencies = []

[project.optional-dependencies]
dev = ["pytest>=7", "ruff>=0.5"]

[project.scripts]
efmcalc = "efmcalc.__main__:main"

[build-system]
requires = ["setuptools>=68"]
build-backend = "setuptools.build_meta"

[tool.ruff]
line-length = 100

[tool.ruff.lint.per-file-ignores]
"tests/test_*.py" = ["S101"]
